name: Build APK

on:
  push:
    branches:
      - main   # or "master" depending on your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk unzip git wget
          pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android Build Tools
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          yes | $HOME/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-30"

      - name: Set ANDROID_HOME
        run: echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NaughtyOrNiceScanner
          path: bin/*.apk
